

# 填写 [ica] 但不填写此项则不启用 ica
enable_ica = true # 是否启用 ica
# 填写 [matrix] 但不填写此项则不启用 matrix
enable_matrix = true # 是否启用 matrix

enable_py = true # 是否启用 python 插件

[py]

# python 插件路径
plugin_path = "/path/to/your/plugin"
config_path = "/path/to/your/config"

[ica]

private_key = "" # 与 icalingua 客户端使用的 private_key 一致
host = ""  # docker 版 icalingua 服务的地址
self_id = 0 # 机器人的 qq 号

# 启动时通知的群号/人
notice_room = [-0] # 启动 bot 后通知的群号/人
# 群号请使用群号的负数
notice_start = true # 是否在启动 bot 后通知

# 机器人的管理员
admin_list = [0] # 机器人的管理员
# 过滤的人
filter_list = [0]

[matrix]

home_server = "" # matrix 服务器地址
bot_id = "" # 机器人的 id
bot_password = "" # 机器人的密码

# 启动时通知的房间
notice_room = [""] # 启动 bot 后通知的房间
notice_start = true # 是否在启动 bot 后通知
