
private_key = "" # 与 icalingua 客户端使用的 private_key 一致
host = ""  # docker 版 icalingua 服务的地址
self_id = 0 # 机器人的 qq 号

# 启动时通知的群号/人
notice_room = [-0] # 启动 bot 后通知的群号/人
# 群号请使用群号的负数
notice_start = true # 是否在启动 bot 后通知

# 机器人的管理员
admin_list = [0] # 机器人的管理员
# 过滤的人
filter_list = [0]

# python 插件路径
py_plugin_path = "/path/to/your/plugin"
py_config_path = "/path/to/your/config"
