[package]
name = "ica-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ed25519 = "2.2.3"
ed25519-dalek = "2.1.0"
hex = "0.4.3"
rust_socketio = "0.4.4"
serde_json = "1.0.108"

[patch.crates-io]
rust_socketio = { path = "V:/githubs/rust-socketio/socketio" }