[package]
name = "ica-rs"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ed25519 = "2.2.3"
ed25519-dalek = "2.1.1"
hex = "0.4.3"
rust_socketio = "0.4.4"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4.34"
toml = "0.8.10"

colored = "2.1.0"

tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["time"] }

[dependencies.pyo3]
version = "0.20.2"

[patch.crates-io]
rust_socketio = { git = "https://github.com/shenjackyuanjie/rust-socketio.git", branch = "mult_payload" }
