[package]
name = "ica-rs"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ed25519 = "2.2.3"
ed25519-dalek = "2.1.0"
hex = "0.4.3"
rust_socketio = "0.4.4"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.108"
toml = "0.8.8"

colored = "2.1.0"
# inline-python = "0.12.0"

[dependencies.pyo3]
version = "0.20.2"
# features = ["auto-initialize"]

[patch.crates-io]
rust_socketio = { path = "D:/githubs/rust-socketio/socketio" }

[build-dependencies]

