[package]
name = "ica-rs"
version = "0.4.12"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ed25519 = "2.2.3"
ed25519-dalek = "2.1.1"
hex = "0.4.3"
rust_socketio = { version = "0.4.4", features = ["async"]}

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4.34"
toml = "0.8.10"
colored = "2.1.0"

tokio = { version = "1.0", features = ["full"] }
futures-util = "0.3.30"
pyo3 = "0.20.3"
# pyo3-async = "0.3.2"
pyo3-asyncio = { version = "0.20.0", features = ["attributes", "tokio-runtime"] }

tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["time"] }
